### ISSUE TITLE
[kdeconnect-kde] Error upgrading: "The remote file either doesn't exist, is unauthorized, or is forbidden "

### ISSUE THREAD

**Issue by maxprehl** [AndreAugustoAAQ/chocolatey-packages#3]
I'm getting the following error when attempting `cup kdeconnect-kde`.

I have no idea if this is on your side or KDE's side, but the URL for the exe is returning a 404.

> Attempt to get headers for https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/1156/artifact/kdeconnect-kde-22.08.3-1156-windows-msvc2019_64-cl.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/1156/artifact/kdeconnect-kde-22.08.3-1156-windows-msvc2019_64-cl.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading kdeconnect-kde
  from 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/1156/artifact/kdeconnect-kde-22.08.3-1156-windows-msvc2019_64-cl.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/1156/artifact/kdeconnect-kde-22.08.3-1156-windows-msvc2019_64-cl.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
  kdeconnect-kde may be able to be automatically uninstalled.
The upgrade of kdeconnect-kde was NOT successful.

**Comment by AndreAugustoDev** [comment]
This problem you had is due to the exe being deleted from the server
It's a known issue but I can't do much about it other than switching to stable software versions
But for the moment I just fixed the url that was modified on the server and it was breaking the package
