### ISSUE TITLE
kde connect fails to install due to invalid link leading to 404

### ISSUE THREAD

**Issue by Ingegneus** [AndreAugustoAAQ/chocolatey-packages#6]
choco install kdeconnect-kde -y
Chocolatey v2.2.2
Installing the following packages:
kdeconnect-kde
By installing, you accept licenses for the packages.
Progress: Downloading kdeconnect-kde 23.04.0.1337... 100%

kdeconnect-kde v23.4.0.1337 [Approved]
kdeconnect-kde package files install completed. Performing other installation steps.
Attempt to get headers for https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-23.04.0-1337-windows-cl-msvc2019-x86_64.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-23.04.0-1337-windows-cl-msvc2019-x86_64.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading kdeconnect-kde
  from 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-23.04.0-1337-windows-cl-msvc2019-x86_64.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-23.04.0-1337-windows-cl-msvc2019-x86_64.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of kdeconnect-kde was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\kdeconnect-kde\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - kdeconnect-kde (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\kdeconnect-kde\tools\ChocolateyInstall.ps1'.
 See log for details.

**Comment by yan12125** [comment]
There is a new version that points to the correct URL: https://community.chocolatey.org/packages/kdeconnect-kde/24.2.0

That version failed automated package validation, though. I guess it can be fixed by replacing `url = ` with `url64 = ` here:

https://github.com/AndreAugustoDev/chocolatey-packages/blob/ff202d11cb13ec9c4d1c9487cd074011b5664b9d/kdeconnect-kde/tools/ChocolateyInstall.ps1#L8

Update: proposed as #7
